# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            My Blog
tagline:          'Scribbling my understanding of Favourite topics on Programming'
description:      'Scribbling my understanding of Favourite topics on Programming'
#url:              http://hyde.getpoole.com
#baseurl:          /

author:
  name:           'Afsal Thaj'
  url:            https://github.com/afsalthaj

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/afsalthaj/afsalthaj.github.io
